app/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
# from django.contrib.auth import logout as v_logout
from users.forms import LoginForm
from users import views as user_views




def i18n_javascript(request):
  return admin.site.i18n_javascript(request)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^engines/', include('engines.urls')),
    url(r'^findings/', include('findings.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^scans/', include('scans.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^rules/', include('rules.urls')),
    url(r'^reportings/', include('reportings.urls')),
    url(r'^settings/', include('settings.urls')),
    url(r'^search', include('search.urls')),
    url(r'^', include('users.urls'), name='home'),

    url(r'^login$', user_views.login, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    # url(r'^logout$', v_logout, {'next_page': '/login'}, name='logout'),
    url(r'^signup$', user_views.signup, name='signup'),

    url(r'^admin/jsi18n/', i18n_javascript),

    #url(r'^api-auth/', include('rest_framework.urls')),
    # url(r'^api-auth/', include('rest_framework.urls')),
]

# debug toolbar & download file
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += staticfiles_urlpatterns()

engines/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


urlpatterns = [

    ## WEB templates
    # ex: /engines/list
    url(r'^list$', views.list_engines_view, name='list_engines_view'),
    # ex: /engines/change_status/8
    url(r'^change_status/(?P<engine_id>[0-9]+)$', views.toggle_engine_status, name='toggle_engine_status'),
    # ex: /engines/add
    url(r'^add$', views.add_engine_view, name='add_engine_view'),
    # ex: /engines/edit/1
    url(r'^edit/(?P<engine_id>[0-9]+)$', views.edit_engine_view, name='edit_engine_view'),
    # ex: /engines/info/1
    url(r'^info/(?P<engine_id>[0-9]+)$', views.info_engine_api, name='info_engine_api'),
    # ex: /engines/delete/1
    url(r'^delete/(?P<engine_id>[0-9]+)$', views.delete_engine_view, name='delete_engine_view'),
    # ex: /engines/1/startscan
    #url(r'^(?P<engine_id>[0-9]+)/startscan$', views.startscan_by_engine_id, name='startscan_by_engine_id'),
    # ex: /engines/nmap/startscan
    #url(r'^(?P<engine_name>[a-zA-Z]+)/startscan$', views.startscan_by_engine_name, name='startscan_by_engine_name'),
    # ex: /engines/policies/list
    url(r'^policies/list$', views.list_policies_view, name='list_policies_view'),
    # ex: /engines/policies/add
    url(r'^policies/add$', views.add_policy_view, name='add_policy_view'),
    # ex: /engines/policies/delete/2
    url(r'^policies/delete/(?P<policy_id>[0-9]+)$', views.delete_policy_view, name='delete_policy_view'),
    # ex: /engines/policies/edit/2
    url(r'^policies/edit/(?P<policy_id>[0-9]+)$', views.edit_policy_view, name='edit_policy_view'),
    # ex: /engines/policies/duplicate/2
    url(r'^policies/duplicate/(?P<policy_id>[0-9]+)$', views.duplicate_policy_view, name='duplicate_policy_view'),
    # ex: /engines/policies/import
    url(r'^policies/import$', views.import_policies_view, name='import_policies_view'),
    # ex: /engines/policies/export/2
    url(r'^policies/export/(?P<policy_id>[0-9]+)$', views.export_policy, name='export_policy'),
    # ex: /engines/policies/export
    url(r'^policies/export$', views.export_policies, name='export_policies'),
    # ex: /engines/types/list
    url(r'^types/list$', views.list_engine_types_view, name='list_engine_types_view'),
    # ex: /engines/types/add
    url(r'^types/add$', views.add_engine_types_view, name='add_engine_types_view'),
    # ex: /engines/types/edit/1
    url(r'^types/edit/(?P<engine_id>[0-9]+)$', views.edit_engine_type_view, name='edit_engine_type_view'),
    # ex: /engines/types/delete/1
    url(r'^types/delete/(?P<engine_id>[0-9]+)$', views.delete_engine_type_view, name='delete_engine_type_view'),

    ## JSON API
    # ex: /engines/
    url(r'^$', views.list_engines, name='list_engines'),
    # ex: /engines/refresh
    url(r'^refresh$', views.refresh_engines_status, name='refresh_engines_status'),
    # ex: /engines/autorefresh
    url(r'^autorefresh$', views.toggle_autorefresh_engine_status, name='toggle_autorefresh_engine_status'),
    # ex: /engines/1
    url(r'^(?P<engine_id>[0-9]+)$', views.list_instances_by_id, name='list_instances_by_id'),
    # ex: /engines/nmap
    url(r'^(?P<engine_name>[a-zA-Z]+)$', views.list_instances_by_name, name='list_instances_by_name'),
    # ex: /engines/1/status
    url(r'^(?P<engine_id>[0-9]+)/status$', views.get_engine_status, name='get_engine_status'),
    # ex: /engines/1/refresh
    url(r'^(?P<engine_id>[0-9]+)/refresh$', views.get_engine_status, name='get_engine_status'),

    # ex: /engines/1/info
    url(r'^(?P<engine_id>[0-9]+)/info$', views.get_engine_info, name='get_engine_info'),
    # ex: /engines/nmap/policies
    url(r'^(?P<engine_name>[a-zA-Z]+)/policies$', views.list_policies_by_engine, name='list_policies_by_engine'),
    # ex: /engines/types
    url(r'^types$', views.list_engine_types, name='list_engine_types'),

    # ex: /engines/api/v1/list
    url(r'^api/v1/list$', views.list_engines_api, name='list_engines_api'),

    # ex: /engines/nmap/startscan
    #url(r'^(?P<engine_name>[a-zA-Z]+)/startscan$', views.startscan_by_engine_name, name='startscan_by_engine_name'),
    # ex: /engines/1/statuslong
    #url(r'^(?P<engine_id>[0-9]+)/statuslong$', views.get_engine_status_long, name='get_engine_status_long'),
    # ex: /engines/1/periodic
    #url(r'^(?P<engine_id>[0-9]+)/periodic$', views.set_periodic_scan, name='set_periodic_scan'),
]

engines/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from events.models import Event
from app.settings import MEDIA_ROOT
import jsonfield, datetime, os, base64

ENGINE_INSTANCE_STATUS = ['STOPPED', 'READY', 'WORKING', 'ERROR']
API_AUTH_METHODS = (
    ('None', 'None'),
    ('HTTPBasic', 'HTTPBasic'),
    ('APIKEY', 'APIKEY')
)

class Engine(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    allowed_asset_types = models.TextField(null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    # class Meta:
    #     db_table = 'engines'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        if not self._state.adding:
            self.updated_at = timezone.now()
        return super(Engine, self).save(*args, **kwargs)

@receiver(post_save, sender=Engine)
def engine_create_update_log(sender, **kwargs):
    if kwargs['created']:
        Event.objects.create(message="[Engine] New engine created (id={}): {}".format(kwargs['instance'].id, kwargs['instance']),
                             type="CREATE", severity="DEBUG")
    else:
        Event.objects.create(message="[Engine] Engine '{}' modified (id={})".format(kwargs['instance'], kwargs['instance'].id),
                             type="UPDATE", severity="DEBUG")

@receiver(post_delete, sender=Engine)
def engine_delete_log(sender, **kwargs):
    Event.objects.create(message="[Engine] Engine '{}' deleted (id={})".format(kwargs['instance'], kwargs['instance'].id),
                 type="DELETE", severity="DEBUG")

class EngineInstance(models.Model):
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True)
    version = models.CharField(max_length=20)
    api_url = models.CharField(max_length=256)
    enabled = models.BooleanField(default=True)
    status = models.CharField(max_length=20, default='idle')
    authentication_method = models.CharField(
        choices=API_AUTH_METHODS, default='None', max_length=10)
    api_key = models.CharField(max_length=100, null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    options = jsonfield.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    # class Meta:
    #     db_table = 'engineinstances'

    def set_status(self, status):
        # Check allowed status values
        if status in ENGINE_INSTANCE_STATUS:
            self.status = status
        else:
            return -1

    def save(self, *args, **kwargs):
        if not self._state.adding:
            self.updated_at = timezone.now()
        return super(EngineInstance, self).save(*args, **kwargs)

    def __str__(self):
        return "{}@{}".format(self.name, self.api_url)

@receiver(post_save, sender=EngineInstance)
def engineinstance_create_update_log(sender, **kwargs):
    if kwargs['created']:
        Event.objects.create(message="[EngineInstance] New engine instance created (id={}): {}".format(kwargs['instance'].id, kwargs['instance']),
                             type="CREATE", severity="DEBUG")
    else:
        Event.objects.create(message="[EngineInstance] Engine instance '{}' modified (id={})".format(kwargs['instance'], kwargs['instance'].id),
                             type="UPDATE", severity="DEBUG")

@receiver(post_delete, sender=EngineInstance)
def engineinstance_delete_log(sender, **kwargs):
    Event.objects.create(message="[EngineInstance] Engine instance '{}' deleted (id={})".format(kwargs['instance'], kwargs['instance'].id),
                 type="DELETE", severity="DEBUG")

# def user_directory_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'user_{0}/{1}'.format(instance.user.id, filename)


class EnginePolicyScope(models.Model):
    name        = models.CharField(max_length=250)
    priority    = models.IntegerField(null=True, blank=True)
    created_at  = models.DateTimeField(default=timezone.now)
    updated_at  = models.DateTimeField(default=timezone.now)

    # class Meta:
    #     db_table = 'engine_policy_scopes'

    def save(self, *args, **kwargs):
        if not self._state.adding:
            self.updated_at = timezone.now()
        return super(EnginePolicyScope, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

@receiver(post_save, sender=EnginePolicyScope)
def enginepolicyscope_create_update_log(sender, **kwargs):
    if kwargs['created']:
        Event.objects.create(message="[EnginePolicyScope] New engine policy scope created (id={}): {}".format(kwargs['instance'].id, kwargs['instance']),
                             type="CREATE", severity="DEBUG")
    else:
        Event.objects.create(message="[EnginePolicyScope] Engine policy scope '{}' modified (id={})".format(kwargs['instance'], kwargs['instance'].id),
                             type="UPDATE", severity="DEBUG")

@receiver(post_delete, sender=EnginePolicyScope)
def enginepolicyscope_delete_log(sender, **kwargs):
    Event.objects.create(message="[EnginePolicyScope] Engine policy scope '{}' deleted (id={})".format(kwargs['instance'], kwargs['instance'].id),
                 type="DELETE", severity="DEBUG")


class EnginePolicy(models.Model):
    engine      = models.ForeignKey(Engine, on_delete=models.CASCADE)
    owner       = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    name        = models.CharField(max_length=200)
    default     = models.BooleanField(default=False)
    description = models.CharField(max_length=200)
    options     = jsonfield.JSONField(null=True, blank=True, default="{}")
    file        = models.FileField(upload_to='./policies/', null=True, blank=True)
    status      = models.CharField(max_length=50)    #active / trashed
    is_default  = models.BooleanField(default=False)
    scopes      = models.ManyToManyField(EnginePolicyScope)
    created_at  = models.DateTimeField(default=timezone.now)
    updated_at  = models.DateTimeField(default=timezone.now)

    class Meta:
        #db_table = 'engine_policies'
        verbose_name_plural = 'Engine policies'

    def save(self, *args, **kwargs):
        if not self._state.adding:
            self.updated_at = timezone.now()

        super(EnginePolicy, self).save(*args, **kwargs)

        if self.file.name:
            initial_path = self.file.path

            # /media/policies/NESSUS/2/nessuspolicy.nessus
            new_name = '/'.join(['policies', self.engine.name, str(self.owner.id), os.path.basename(initial_path)])
            new_path = os.path.join(MEDIA_ROOT, 'policies',
                self.engine.name, str(self.owner.id), os.path.basename(initial_path))

            # create /media/policies/<engine_name>/ if not exists
            if not os.path.exists(MEDIA_ROOT+"/policies/"+self.engine.name):
                    os.mkdir(MEDIA_ROOT+"/policies/"+self.engine.name)

            # create /media/policies/<engine_name>/<owner_id> if not exists
            if not os.path.exists(os.path.dirname(new_path)):
                    os.mkdir(os.path.dirname(new_path))
            os.rename(initial_path, new_path)

            self.file.name = new_name

        return super(EnginePolicy, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.file.name and os.path.exists(self.file.path):
            os.remove(self.file.path)
        return super(EnginePolicy, self).delete(*args, **kwargs)

    def __str__(self):
        return "{}@{}".format(self.engine.name, self.name)

    def as_dict(self):
        file_b64 = None
        if self.file:
            file_b64_name = self.file.name.split("/")[-1:][0]
            file_b64_content = ""
            self.file.open(mode='rb')
            file_b64_content += base64.b64encode(self.file.read())
            self.file.close()
            file_b64 = {"filename": file_b64_name, "content": file_b64_content}

        return {
            'id': self.id,
            'name': self.name,
            'engine': self.engine.id,
            'engine_name': self.engine.name,
            'owner': self.owner.id,
            'default': self.default,
            'description': self.description,
            'options': self.options,
            'file': file_b64,
            'status': self.status,
            'scopes': [s.id for s in self.scopes.all()],
            'scope_names': [s.name for s in self.scopes.all()]
        }

@receiver(post_save, sender=EnginePolicy)
def enginepolicy_create_update_log(sender, **kwargs):
    if kwargs['created']:
        Event.objects.create(message="[EnginePolicy] New engine policy created (id={}): {}".format(kwargs['instance'].id, kwargs['instance']),
                             type="CREATE", severity="DEBUG")
    else:
        Event.objects.create(message="[EnginePolicy] Engine policy '{}' modified (id={})".format(kwargs['instance'], kwargs['instance'].id),
                             type="UPDATE", severity="DEBUG")

@receiver(post_delete, sender=EnginePolicy)
def enginepolicy_delete_log(sender, **kwargs):
    Event.objects.create(message="[EnginePolicy] Engine policy '{}' deleted (id={})".format(kwargs['instance'], kwargs['instance'].id),
                 type="DELETE", severity="DEBUG")

engines/templates/add-engine-policy.html
{% extends 'base.html' %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/engines/list">engines</a></li>
  <li><a href="/engines/policies/list">policies</a></li>
  <li class="active">add new policy</li>
</ul>
<div class="container">
  <form action="/engines/policies/add" method="post" class="form-horizontal" enctype="multipart/form-data">
    <legend>Add a new policy</legend>
      {% csrf_token %}
      {% for field in form %}
          {% if field.errors %}
              <div class="form-group has-error">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      <span class="help-block">
                          {% for error in  field.errors %}{{ error }}{% endfor %}
                      </span>
                  </div>
              </div>
          {% elif not field.is_hidden %}
              <div class="form-group">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      {% if field.help_text %}
                          <p class="help-block"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                  </div>
              </div>
          {% endif %}
      {% endfor %}
      <div class="form-group submit-div">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-warning col-sm-12">Create a new policy</button>
        </div>
      </div>
  </form>
</div>

{% endblock %}

engines/templates/add-engine.html
{% extends 'base.html' %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/engines/list">engines</a></li>
  <li><a href="/engines/types/list">types</a></li>
  <li class="active">add new engine type</li>
</ul>

<div class="container">
  <form action="/engines/types/add" method="post" class="form-horizontal">
    <legend>Add a engine type</legend>
      {% csrf_token %}
      {% for field in form %}
          {% if field.errors %}
              <div class="form-group has-error">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      <span class="help-block">
                          {% for error in  field.errors %}{{ error }}{% endfor %}
                      </span>
                  </div>
              </div>
          {% elif not field.is_hidden %}
              <div class="form-group">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      {% if field.help_text %}
                          <p class="help-block"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                  </div>
              </div>
          {% endif %}
      {% endfor %}
      <div class="form-group submit-div">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-warning col-sm-12">Create a new engine type</button>
        </div>
      </div>
  </form>
</div>

{% endblock %}

engines/templates/add-scan-engine.html
{% extends 'base.html' %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/engines/list">engines</a></li>
  <li class="active">add new scan engine</li>
</ul>

<div class="container">
  <form action="/engines/add" method="post" class="form-horizontal">
    <legend>Add a new scan engine</legend>
      {% csrf_token %}
      {% for field in form %}
          {% if field.errors %}
              <div class="form-group has-error">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      <span class="help-block">
                          {% for error in  field.errors %}{{ error }}{% endfor %}
                      </span>
                  </div>
              </div>
          {% elif not field.is_hidden %}
              <div class="form-group">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      {% if field.help_text %}
                          <p class="help-block"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                  </div>
              </div>
          {% endif %}
      {% endfor %}
      <div class="form-group submit-div">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-warning col-sm-12">Create a new engine</button>
        </div>
      </div>

  </form>
</div>

<script>
  $('#id_username').parent().parent().addClass("hidden");
  $('#id_password').parent().parent().addClass("hidden");
  $('#id_api_key').parent().parent().addClass("hidden");

  $('#id_authentication_method').change(function(e){
    if($('#id_authentication_method').val() == "HTTPBasic") {
      $('#id_username').parent().parent().removeClass("hidden");
      $('#id_password').parent().parent().removeClass("hidden");
      $('#id_api_key').parent().parent().addClass("hidden");
    } else if ($('#id_authentication_method').val() == "APIKEY") {
      $('#id_username').parent().parent().addClass("hidden");
      $('#id_password').parent().parent().addClass("hidden");
      $('#id_api_key').parent().parent().removeClass("hidden");
    } else {
      $('#id_username').parent().parent().addClass("hidden");
      $('#id_password').parent().parent().addClass("hidden");
      $('#id_api_key').parent().parent().addClass("hidden");
    }
  });
</script>

{% endblock %}

engines/templates/edit-scan-engine.html
{% extends 'base.html' %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/engines/list">engines</a></li>
  <li class="active">edit engine instance</li>
</ul>

<div class="container">
  <form action="/engines/edit/{{ engine_id }}" method="post" class="form-horizontal">
    <legend>Edit an engine instance</legend>
      {% csrf_token %}
      {% for field in form %}
          {% if field.errors %}
              <div class="form-group has-error">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      <span class="help-block">
                          {% for error in  field.errors %}{{ error }}{% endfor %}
                      </span>
                  </div>
              </div>
          {% elif not field.is_hidden %}
              <div class="form-group">
                  <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-4">
                      {{ field }}
                      {% if field.help_text %}
                          <p class="help-block"><small>{{ field.help_text }}</small></p>
                      {% endif %}
                  </div>
              </div>
          {% endif %}
      {% endfor %}
      <div class="form-group submit-div">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-warning col-sm-12">Update engine</button>
        </div>
      </div>
  </form>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
</div>

<script>
  $('#id_username').parent().parent().addClass("hidden");
  $('#id_password').parent().parent().addClass("hidden");
  $('#id_api_key').parent().parent().addClass("hidden");

  $('#id_authentication_method').change(function(e){
    if($('#id_authentication_method').val() == "HTTPBasic") {
      $('#id_username').parent().parent().removeClass("hidden");
      $('#id_password').parent().parent().removeClass("hidden");
      $('#id_api_key').parent().parent().addClass("hidden");
    } else if ($('#id_authentication_method').val() == "APIKEY") {
      $('#id_username').parent().parent().addClass("hidden");
      $('#id_password').parent().parent().addClass("hidden");
      $('#id_api_key').parent().parent().removeClass("hidden");
    } else {
      $('#id_username').parent().parent().addClass("hidden");
      $('#id_password').parent().parent().addClass("hidden");
      $('#id_api_key').parent().parent().addClass("hidden");
    }
  });
</script>

{% endblock %}

engines/templates/list-engines.html
{% extends 'base.html' %}
{% load patrowl_tags %}
{% block content %}

<ul class="breadcrumb">
  <li><a href="/engines/list">engines</a></li>
  <li class="active">types</li>
</ul>

<div class="container">
  <table class="table table-hover" data-toggle="table" data-sort-name="value" data-sort-order="desc">
    <thead>
      <tr>
        <th data-field="name">Name</th>
        <th data-field="allowed_asset_types">Allowed Asset type</th>
        <th data-field="updated_at">Last update</th>
        <th data-field="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for engine in engines %}
    <tr>
      <td>{{ engine.name }}</td>
      <td>{{ engine.allowed_asset_types }}</td>
      <td>{{ engine.updated_at|smartdate }}</td>
      <td>
        <button type="button" class="btn btn-default btn-xs btn-engine-info" data-toggle="modal" data-target="#modal_info_{{engine.id}}">
          <span class="glyphicon glyphicon-info-sign"></span></button>
        <div id="modal_info_{{engine.id}}" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{{ engine.name }}</h4>
              </div>
              <div class="modal-body">
                <dl class="dl-horizontal">
                  <dt>Name</dt><dd>{{engine.name}}</dd>
                  <dt>Description</dt><dd>{{engine.description}}</dd>
                  <dt>Engines instances</dt><dd>{{engine.engineinstance_set.all|join:", "}}</dd>
                  <dt>Allowed assets</dt><dd>{{engine.allowed_asset_types}}</dd>
                  <dt>Created at</dt><dd>{{engine.created_at|smartdate}}</dd>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <button type="button" class="btn btn-default btn-xs" aria-haspopup="true" aria-expanded="false" onclick="location.href='/engines/types/edit/{{ engine.id }}'">
          <span class="glyphicon glyphicon-edit"></span></button>
        <button type="button" class="btn btn-danger btn-xs" aria-haspopup="true" aria-expanded="false" onclick="location.href='/engines/types/delete/{{ engine.id }}'">
          <span class="glyphicon glyphicon-remove"></span></button>
      </td>
    </tr>
  {% endfor %}
  </tbody>
  </table>
  <a href="/engines/types/add">+ Add a new engine type</a>

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
</div>

<script>

  $(function() {

    // Refresh engine status
    $("button.btn-refresh-engine-status").on('click', function(eventObject) {
      engine_id = eventObject.currentTarget.getAttribute('engine-id')
      engine_url = "/engines/"+engine_id+"/refresh"
      var xhr = $.get(engine_url, function(data) {
        location.reload()
        if (data.status == "success") {
          console.log( "Status successfully refreshed!" );
          $("div.notifications").html('<div class="alert alert-dismissible alert-success fade in"><button type="button" class="close" data-dismiss="alert">&times;</button>Scan successfully enqueued</div>');
          $("div.notifications>div").delay(3000).fadeOut(
            function () {
                $("div.notifications>div").remove();
            }
          );
        }
      })
    });

  });
</script>
{% endblock %}